apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: kind-filebeat
spec:
  type: filebeat
  version: 8.13.4
  config:
    filebeat.autodiscover:
      providers:
        - type: docker
          templates:
            - condition:
                contains:
                  docker.container.image: "your-app"
              config:
                - type: docker
                  containers.ids:
                    - "${data.docker.container.id}"
    processors:
      - add_cloud_metadata: {}
      - add_docker_metadata: {}
    output.logstash:
      hosts: ["logstash.default.svc:5044"]
  daemonSet:
    podTemplate:
      spec:
        hostNetwork: true
        serviceAccountName: filebeat
        containers:
        - name: filebeat
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
        volumes:
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock
